### PR TITLE
fix: Removed mixed space and tabs from templates

### LINKED ISSUE #149: Template containing mixed tabs and spaces causing linting errors
## Package version
Adonis: 5.0.0-preview-rc
Auth: 4.3.1

## Node.js and npm version
12.18.3

## Sample Code (to reproduce the issue)
https://github.com/adonisjs/auth/blob/0d64cf018046d45b98e4c4f2fc708c9944eccedc/templates/middleware/Auth.txt#L26-L35

https://github.com/adonisjs/auth/blob/0d64cf018046d45b98e4c4f2fc708c9944eccedc/templates/config/partials/basic-guard.txt#L1-L19

https://github.com/adonisjs/auth/blob/0d64cf018046d45b98e4c4f2fc708c9944eccedc/templates/contract/partials/basic-guard.txt#L1-L13

Not really a bug, just the templates mixing tabs with spaces and causing the linter to show `Mixed spaces and tabs. eslint(no-mixed-spaces-and-tabs)` errors.

### PR DESCRIPTION
**Pull request by allanmaral**
## Proposed changes

Replaced all the tabs in the `templates/*.txt` files to spaces.
Fix #149 

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/auth/blob/master/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by RomainLanz** [comment]
Hey @allanmaral! 👋 

Could you please also update prettier configuration to ignore those `txt` file?

If you can also made the change here it would be awesome! (https://github.com/adonisjs/mrm-preset/blob/develop/prettier/index.js)

**Comment by allanmaral** [comment]
Hey @RomainLanz 👋
Sure! Created the PR  adonisjs/mrm-preset#13 and updated the `.prettierignore` in this one.

Hope everything is alright, first time contributing

**Comment by thetutlage** [comment]
@RomainLanz Leaving this PR for you to merge :)

**Comment by RomainLanz** [comment]
Thanks! @allanmaral

**Pull request merged**
